### ISSUE TITLE
Bookkeeper daemon is not starting in the cluster nodes

### ISSUE THREAD

**Issue by abhishekdas99** [qubole/rubix#141]
Getting exception during the start of the bookkeeper daemon

```
 ERROR main bookkeeper.BookKeeperServer: Cache directories could not be created
java.io.FileNotFoundException: Cache parent directory /media/ephemeral1 does not exist
        at com.qubole.rubix.spi.CacheUtil.createCacheDirectories(CacheUtil.java:60)
        at com.qubole.rubix.bookkeeper.BookKeeper.initializeCache(BookKeeper.java:370)
        at com.qubole.rubix.bookkeeper.BookKeeper.<init>(BookKeeper.java:86)
        at com.qubole.rubix.bookkeeper.BookKeeperServer.startServer(BookKeeperServer.java:76)
        at com.qubole.rubix.bookkeeper.BookKeeperServer$1.run(BookKeeperServer.java:66)
        at java.lang.Thread.run(Thread.java:748)
        at com.qubole.rubix.bookkeeper.BookKeeperServer.run(BookKeeperServer.java:69)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
        at com.qubole.rubix.bookkeeper.BookKeeperServer.main(BookKeeperServer.java:55)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorI

```

**Comment by abhishekdas99** [comment]
Closed by https://github.com/qubole/rubix/commit/a9b5ff958168c15729b64f895f11a95a5f748a78
