### ISSUE TITLE
Some task attempts are failing with ArrayIndexOutOfBoundsException with Asynchronous Cache Warmup enabled

### ISSUE THREAD

**Issue by abhishekdas99** [qubole/rubix#204]
Some tasks of a job that is warming up the cache are failing with ArrayIndexOutOfBoundsException

**Job Type :** Hive on Tez Query (The same thing is reproducible with Spark as well)
**Initial Run or Subsequent Run:** Initial Run
**Status of the Job:** The job succeeds (with some task attempt failure)
**Status of subsequent run of the same job:** The subsequent runs of the same jobs succeed.
**Data Corruption:** No

The stack of the exception:

```
2018-09-06 20:32:40,938 INFO [TezChild] task.TezTaskRunner: Encounted an error while executing task: attempt_1536264376320_0001_1_02_000044_2
java.lang.RuntimeException: java.lang.RuntimeException: java.io.IOException: java.lang.ArrayIndexOutOfBoundsException
	at org.apache.hadoop.hive.ql.exec.tez.TezProcessor.initializeAndRunProcessor(TezProcessor.java:171)
	at org.apache.hadoop.hive.ql.exec.tez.TezProcessor.run(TezProcessor.java:137)
	at org.apache.tez.runtime.LogicalIOProcessorRuntimeTask.run(LogicalIOProcessorRuntimeTask.java:337)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable$1.run(TezTaskRunner.java:179)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable$1.run(TezTaskRunner.java:171)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:421)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1635)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable.callInternal(TezTaskRunner.java:171)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable.callInternal(TezTaskRunner.java:167)
	at org.apache.tez.common.CallableWithNdc.call(CallableWithNdc.java:36)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.io.IOException: java.lang.ArrayIndexOutOfBoundsException
	at org.apache.hadoop.mapred.split.TezGroupedSplitsInputFormat$TezGroupedSplitsRecordReader.initNextRecordReader(TezGroupedSplitsInputFormat.java:192)
	at org.apache.hadoop.mapred.split.TezGroupedSplitsInputFormat$TezGroupedSplitsRecordReader.<init>(TezGroupedSplitsInputFormat.java:131)
	at org.apache.hadoop.mapred.split.TezGroupedSplitsInputFormat.getRecordReader(TezGroupedSplitsInputFormat.java:97)
	at org.apache.tez.mapreduce.lib.MRReaderMapred.setupOldRecordReader(MRReaderMapred.java:149)
	at org.apache.tez.mapreduce.lib.MRReaderMapred.setSplit(MRReaderMapred.java:80)
	at org.apache.tez.mapreduce.input.MRInput.initFromEventInternal(MRInput.java:614)
	at org.apache.tez.mapreduce.input.MRInput.initFromEvent(MRInput.java:593)
	at org.apache.tez.mapreduce.input.MRInputLegacy.checkAndAwaitRecordReaderInitialization(MRInputLegacy.java:141)
	at org.apache.tez.mapreduce.input.MRInputLegacy.init(MRInputLegacy.java:109)
	at org.apache.hadoop.hive.ql.exec.tez.MapRecordProcessor.getMRInput(MapRecordProcessor.java:372)
	at org.apache.hadoop.hive.ql.exec.tez.MapRecordProcessor.init(MapRecordProcessor.java:129)
	at org.apache.hadoop.hive.ql.exec.tez.TezProcessor.initializeAndRunProcessor(TezProcessor.java:147)
	... 14 more
Caused by: java.io.IOException: java.lang.ArrayIndexOutOfBoundsException
	at org.apache.hadoop.hive.io.HiveIOExceptionHandlerChain.handleRecordReaderCreationException(HiveIOExceptionHandlerChain.java:97)
	at org.apache.hadoop.hive.io.HiveIOExceptionHandlerUtil.handleRecordReaderCreationException(HiveIOExceptionHandlerUtil.java:57)
	at org.apache.hadoop.hive.ql.io.HiveInputFormat.getRecordReader(HiveInputFormat.java:253)
	at org.apache.hadoop.mapred.split.TezGroupedSplitsInputFormat$TezGroupedSplitsRecordReader.initNextRecordReader(TezGroupedSplitsInputFormat.java:189)
	... 25 more
Caused by: java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:280)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at org.apache.hadoop.hive.ql.io.orc.RecordReaderUtils.readDiskRanges(RecordReaderUtils.java:272)
	at org.apache.hadoop.hive.ql.io.orc.RecordReaderImpl.readPartialDataStreams(RecordReaderImpl.java:964)
	at org.apache.hadoop.hive.ql.io.orc.RecordReaderImpl.readStripe(RecordReaderImpl.java:793)
	at org.apache.hadoop.hive.ql.io.orc.RecordReaderImpl.advanceStripe(RecordReaderImpl.java:986)
	at org.apache.hadoop.hive.ql.io.orc.RecordReaderImpl.advanceToNextRow(RecordReaderImpl.java:1019)
	at org.apache.hadoop.hive.ql.io.orc.RecordReaderImpl.<init>(RecordReaderImpl.java:205)
	at org.apache.hadoop.hive.ql.io.orc.ReaderImpl.rowsOptions(ReaderImpl.java:498)
	at org.apache.hadoop.hive.ql.io.orc.OrcRawRecordMerger$ReaderPair.<init>(OrcRawRecordMerger.java:184)
	at org.apache.hadoop.hive.ql.io.orc.OrcRawRecordMerger$OriginalReaderPair.<init>(OrcRawRecordMerger.java:227)
	at org.apache.hadoop.hive.ql.io.orc.OrcRawRecordMerger.<init>(OrcRawRecordMerger.java:440)
	at org.apache.hadoop.hive.ql.io.orc.OrcInputFormat.getReader(OrcInputFormat.java:1293)
	at org.apache.hadoop.hive.ql.io.orc.OrcInputFormat.getRecordReader(OrcInputFormat.java:1193)
	at org.apache.hadoop.hive.ql.io.HiveInputFormat.getRecordReader(HiveInputFormat.java:251)
	... 26 more
```

**Comment by abhishekdas99** [comment]
Logs from the task:

```
2018-10-02 01:59:58,152 INFO [TezChild] core.CachingInputStream: Got Read, currentPos: 54014 currentBlock: 0 bufferOffset: 0 length: 1048576
2018-10-02 01:59:58,153 INFO [TezChild] core.CachingInputStream: Sending block 0 to NonLocalRequestChain to node : ip-10-0-0-68.ec2.internal
2018-10-02 01:59:58,153 INFO [TezChild] core.NonLocalRequestChain:  Trying to getCacheStatus from : ip-10-0-0-68.ec2.internal for file : s3://qubole-karma/perf/data/tpcds/orc/scale_100/store_sales/000317 StartBlock : 0 EndBlock : 2
2018-10-02 01:59:58,153 INFO [TezChild] core.NonLocalRequestChain: Cache Status : [BlockLocation(location:LOCAL, remoteLocation:ip-10-0-0-68.ec2.internal), BlockLocation(location:LOCAL, remoteLocation:ip-10-0-0-68.ec2.internal)]
2018-10-02 01:59:58,153 INFO [TezChild] core.ReadRequestChain: Request to add ReadRequest: [0, 1048576, 54014, 1048576, 0]
2018-10-02 01:59:58,153 INFO [TezChild] core.ReadRequestChain: Added ReadRequest: [0, 1048576, 54014, 1048576, 0]
2018-10-02 01:59:58,154 INFO [TezChild] core.ReadRequestChain: Request to add ReadRequest: [0, 1048576, 54014, 1048576, 0]
2018-10-02 01:59:58,154 INFO [TezChild] core.ReadRequestChain: Added ReadRequest: [0, 1048576, 54014, 1048576, 0]
2018-10-02 01:59:58,154 INFO [TezChild] core.CachingInputStream: Sending block 1 to NonLocalRequestChain to node : ip-10-0-0-68.ec2.internal
2018-10-02 01:59:58,154 INFO [TezChild] core.ReadRequestChain: Request to add ReadRequest: [1048576, 2097152, 1048576, 1102590, 994562]
2018-10-02 01:59:58,154 INFO [TezChild] core.ReadRequestChain: Updated last to: [0, 2097152, 54014, 1102590, 0]
2018-10-02 01:59:58,154 INFO [TezChild] core.ReadRequestChain: Request to add ReadRequest: [1048576, 2097152, 1048576, 1102590, 994562]
2018-10-02 01:59:58,154 INFO [TezChild] core.ReadRequestChain: Added ReadRequest: [1048576, 2097152, 1048576, 1102590, 994562]
2018-10-02 01:59:58,154 INFO [TezChild] core.CachingInputStream: Executing Chains
2018-10-02 01:59:58,154 INFO [TezChild] core.NonLocalRequestChain: Executing NonLocalRequestChain 
2018-10-02 01:59:58,158 INFO [TezChild] core.RemoteFetchRequestChain: RemoteFetchRequest from : ip-10-0-0-68.ec2.internal Start : 0 of length 2097152
2018-10-02 01:59:58,159 INFO [TezChild] core.RemoteFetchRequestChain: Send request to remote took 5 :msecs
2018-10-02 01:59:58,159 INFO [TezChild] core.NonLocalRequestChain: NonLocalRequest took : 5 msecs 
2018-10-02 01:59:58,323 INFO [TezChild] core.DirectReadRequestChain: Read 1102590 bytes directly from remote, no caching
2018-10-02 01:59:58,324 INFO [TezChild] core.CachingInputStream: Read 1102590 bytes
```
