### ISSUE TITLE
Bookeeper reports java.util.MissingFormatArgumentException instead root cause on read error

### ISSUE THREAD

**Issue by losipiuk** [qubole/rubix#362]
If there is problem accessing `FileStatus` followinig exception is logged:

```
2020-04-28T15:42:54.166Z        ERROR   20200428_154213_00045_9zr37.9.0-596-72  com.qubole.rubix.core.CachingInputStream        Could not get FileInfo for s3://starburstdata-datasets/tpcds-sf1000-ORC/store_sales/20180108_203540_00368_ecxdi_b409d2ed-cd4f-4899-8cd1-5e2d39ceb31e. Fetching FileStatus from remote file system :
java.util.MissingFormatArgumentException: Format specifier '%s'
        at java.base/java.util.Formatter.format(Formatter.java:2672)
        at java.base/java.util.Formatter.format(Formatter.java:2609)
        at java.base/java.lang.String.format(String.java:2897)
        at com.qubole.rubix.bookkeeper.BookKeeper.getFileInfo(BookKeeper.java:415)
        at com.qubole.rubix.spi.LocalBookKeeperClient.getFileInfo(LocalBookKeeperClient.java:76)
        at com.qubole.rubix.core.CachingInputStream.<init>(CachingInputStream.java:106)
        at com.qubole.rubix.core.CachingFileSystem.open(CachingFileSystem.java:168)
        at org.apache.hadoop.fs.PrestoFileSystemCache$FileSystemWrapper.open(PrestoFileSystemCache.java:327)
        at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:899)
        at io.prestosql.plugin.hive.orc.OrcPageSourceFactory.lambda$createOrcPageSource$0(OrcPageSourceFactory.java:217)
```

Root cause should be logged instead `MissingFormatArgumentException`

**Comment by raunaqmorarka** [comment]
Fixed with https://github.com/qubole/rubix/pull/363
Thanks!
