### ISSUE TITLE
Presto error - no nodes available to run query

### ISSUE THREAD

**Issue by pvam** [qubole/rubix#37]
With RUBIX enabled, running multiple queries on presto cluster causes 'No nodes available to run query' error.

> **cluster configs**

m3.xlarge
min=1
rubix enabled
presto version =0.119, 0.142
Query - 

> SELECT * FROM tpcds_orc_100.store_sales where ss_customer_sk=1000

Ran 10 instances of the above query. Some were successful others weren't. 
```
Query 20161118_124345_00020_98npx failed: No nodes available to run query
com.facebook.presto.spi.PrestoException: No nodes available to run query
at com.facebook.presto.util.Failures.checkCondition(Failures.java:75)
at com.facebook.presto.execution.NodeScheduler$NodeSelector.computeAssignments(NodeScheduler.java:278)
at com.facebook.presto.execution.scheduler.SplitPlacementPolicy.computeAssignments(SplitPlacementPolicy.java:41)
at com.facebook.presto.execution.scheduler.SourcePartitionedScheduler.schedule(SourcePartitionedScheduler.java:99)
at com.facebook.presto.execution.scheduler.SqlQueryScheduler.schedule(SqlQueryScheduler.java:295)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
```

Internally, presto server is crashing because of java is running out of memory. More specifically, RemoteReadRequestChain of the Cache subsystem allocates 2 buffers namely prefix and suffix buffer to hold the block data which is outside the requested block range. This will later be written to disk along with requested data to serve future I/O requests. In a concurrent environment, there can be thousands of these ReadRequests in RemoteReadRequestChain which results in allocating many small ByteBuffers (each of block size). Its is possible that before Garbage Collector kicks in and frees up this space, JVM is running out of memory and raising a SIGINT signal. JVM eventually shuts down bringing down presto server.

**Comment by pvam** [comment]
This got fixed in v2.6.
